services:
    sam_business_right.type:
        class: "CanalTP\\SamEcoreSecurityBundle\\Form\\Type\\Permission\\BusinessRightType"
        arguments:
           - '@sam.business_component'
           - @security.context
        tags:
            - { name: form.type }
