services:
    sam_create_role.type:
        class: "CanalTP\SamEcoreSecurityBundle\Form\Type\Role\CreateRoleType"
        arguments:
           - '@sam_create_role_listener'
        tags:
            - { name: form.type }

    sam_create_role_listener:
        class: "CanalTP\SamEcoreSecurityBundle\Form\EventListener\CreateRoleListener"
        arguments:
           - '@doctrine.orm.entity_manager'

    sam_copy_role_by_application.type:
        class: "CanalTP\SamEcoreSecurityBundle\Form\Type\Role\CopyRoleByApplicationType"
        arguments:
            - '@translator'
        tags:
            - { name: form.type }
